name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git zip unzip openjdk-11-jdk build-essential
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer==2.1.0

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my_kivy_app_apk
        path: bin/*.apk
