name: Build Python EXE with Nuitka

# Workflow tetikleme
on:
  push:
    branches:
      - main        # main branch’e push olunca otomatik çalışır
  workflow_dispatch: # manuel tetikleme de mümkün

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      # 1️⃣ Repo’yu çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Python kur
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Dependencies yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install nuitka

      # 4️⃣ EXE build et
      - name: Build EXE
        run: |
          nuitka --onefile main.py

      # 5️⃣ Artifact olarak yükle
      - name: Upload EXE
        uses: actions/upload-artifact@v4
